/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package message;

import java.awt.Dimension;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author busra
 */
public class sohbet extends javax.swing.JFrame {

    /**
     * Creates new form sohbet
     */
    public static sohbet ThisSohbet;
    public DefaultListModel kisi;
    public static boolean durum;

    public sohbet() {
        initComponents();
        ThisSohbet = this;
        ThisSohbet.setPreferredSize(new Dimension(450, 640));
        durum = false;
    }

    public sohbet(String s) throws InterruptedException {
        initComponents();
        ThisSohbet = this;
        ThisSohbet.setPreferredSize(new Dimension(450, 640));
        durum = false;
        Thread.sleep(300);
        String kisi = s;
        mesajlasilan_kisi.setText(kisi.toString());
    }

    public sohbet(String s, int i) throws InterruptedException {
        initComponents();
        ThisSohbet = this;
        ThisSohbet.setPreferredSize(new Dimension(450, 640));
        durum = true;
        Thread.sleep(500);
        String[] parts3 = s.split("_");
        String mesajlasilan_adi = parts3[0];
        String icerik = parts3[1];
        ThisSohbet.mesajlasilan_kisi.setText(mesajlasilan_adi);
        ThisSohbet.mesaj_akisi.setText(icerik);
        Thread.sleep(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mesajlasilan_kisi = new javax.swing.JLabel();
        yollanan_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mesaj_akisi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 640));
        setMinimumSize(new java.awt.Dimension(450, 640));
        setResizable(false);

        mesajlasilan_kisi.setBackground(new java.awt.Color(0, 102, 255));
        mesajlasilan_kisi.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        mesajlasilan_kisi.setForeground(new java.awt.Color(255, 255, 255));
        mesajlasilan_kisi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesajlasilan_kisi.setOpaque(true);

        yollanan_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/message/send.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/message/back.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        mesaj_akisi.setColumns(20);
        mesaj_akisi.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        mesaj_akisi.setLineWrap(true);
        mesaj_akisi.setRows(5);
        mesaj_akisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jScrollPane1.setViewportView(mesaj_akisi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(yollanan_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mesajlasilan_kisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(mesajlasilan_kisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(yollanan_txt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //anasayfaya geri donmek icin kullanilir.
        ThisSohbet.dispose();
        anasayfa.ThisAnasayfa.setVisible(true);
        durum = false;
        try {
            Thread.sleep(200);
        } catch (InterruptedException ex) {
            Logger.getLogger(sohbet.class.getName()).log(Level.SEVERE, null, ex);
        }
        Message msg = new Message(Message.Message_Type.baglantiKopar);
        msg.content = mesajlasilan_kisi.getText().toString();
        client.Client.Send(msg);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        //text kutusuna yazilan mesaji genel mesaj akisina iletir ve karsi clienta gonderir
        if (durum == false) {
            String ad = client.Client.client_name;
            String n_ad = ad.toUpperCase();
            String icerik = n_ad + ":\n" + yollanan_txt.getText().toString() + "\n";
            mesaj_akisi.setText(mesaj_akisi.getText() + icerik);
            yollanan_txt.setText("");

            Message msg = new Message(Message.Message_Type.kisiBul);
            msg.content = mesajlasilan_kisi.getText().toString() + "-" + client.Client.client_name + "_" + mesaj_akisi.getText();
            try {
                Thread.sleep(300);
            } catch (InterruptedException ex) {
                Logger.getLogger(sohbet.class.getName()).log(Level.SEVERE, null, ex);
            }
            durum = true;
            client.Client.Send(msg);
        } else {
            String ad = client.Client.client_name;
            String n_ad = ad.toUpperCase();
            String icerik = n_ad + ":\n" + yollanan_txt.getText().toString() + "\n";
            mesaj_akisi.setText(mesaj_akisi.getText() + icerik);
            yollanan_txt.setText("");
            Message msg = new Message(Message.Message_Type.icerik2);
            msg.content = mesajlasilan_kisi.getText().toString() + "_" + mesaj_akisi.getText();
            try {
                Thread.sleep(300);
            } catch (InterruptedException ex) {
                Logger.getLogger(sohbet.class.getName()).log(Level.SEVERE, null, ex);
            }
            client.Client.Send(msg);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sohbet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sohbet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sohbet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sohbet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sohbet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea mesaj_akisi;
    public javax.swing.JLabel mesajlasilan_kisi;
    private javax.swing.JTextField yollanan_txt;
    // End of variables declaration//GEN-END:variables
}
